export const makeSelectStyles = {
  control: (baseStyles, { isHover }) => ({
    ...baseStyles,
    border: 'none',
    width: 224,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#F7F7FB',
    color: '#121417',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '20px',
  }),
  placeholder: styles => ({
    ...styles,
    color: '#121417',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '20px',
  }),
  menuList: styles => ({
    ...styles,
    borderRadius: '14px',
    border: '1px solid rgba(18, 20, 23, 0.05)',
    background: '#FFF',
    boxShadow: '0px 4px 36px 0px rgba(0, 0, 0, 0.02)',
  }),
  option: (baseStyles, { isFocused }) => ({
    ...baseStyles,
    color: isFocused ? '#121417' : 'rgba(18, 20, 23, 0.20)',
    backgroundColor: isFocused ? 'none' : 'none',
    cursor: 'pointer',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWweight: '500',
    lineHeight: '20px',
  }),
};

export const priceSelectStyles = {
  control: (baseStyles, { isHover }) => ({
    ...baseStyles,
    border: isHover ? 'none' : 'none',
    width: 125,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#F7F7FB',
    color: '#121417',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '20px',
    paddingLeft: 32,
  }),
  placeholder: styles => ({
    ...styles,
    color: '#121417',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '20px',
  }),
  menuList: styles => ({
    ...styles,
    borderRadius: '14px',
    border: '1px solid rgba(18, 20, 23, 0.05)',
    background: '#FFF',
    boxShadow: '0px 4px 36px 0px rgba(0, 0, 0, 0.02)',
  }),
  option: (baseStyles, { isFocused }) => ({
    ...baseStyles,
    color: isFocused ? '#121417' : 'rgba(18, 20, 23, 0.20)',
    backgroundColor: isFocused ? 'none' : 'none',
    cursor: 'pointer',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWweight: '500',
    lineHeight: '20px',
  }),
};
